name = "NiSparseArrays"
uuid = "b3c78db8-5351-4c94-92cb-e6a7a02f3abe"
authors = ["JieLi"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
